language: node_js
node_js:
  - 14
# branchs:
#   only:
#     - master
cache:
  directories:
    - node_modules
before_install:
  - cd ./npm-publish/simple-lodash
install:
  - npm install
scripts:
  - npm run test
